# Generated by Django 4.2.16 on 2024-12-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("film_log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="user",),
        migrations.RemoveField(model_name="watchlist", name="user",),
        migrations.AddField(
            model_name="review",
            name="userProfile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="film_log.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="watchlist",
            name="userProfile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="film_log.userprofile",
            ),
            preserve_default=False,
        ),
    ]
