# Generated by Django 4.2.16 on 2024-12-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("film_log", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="userProfile",),
        migrations.AddField(
            model_name="review",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="film_log.userprofile",
            ),
            preserve_default=False,
        ),
    ]
