# Generated by Django 4.2.16 on 2024-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0002_statusmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
