# Generated by Django 4.2.16 on 2024-10-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0005_alter_image_status_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusmessage",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.DeleteModel(name="Image",),
    ]
