# Generated by Django 4.2.16 on 2024-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0006_statusmessage_image_file_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusmessage",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="status_images/"),
        ),
    ]
