# Generated by Django 4.2.16 on 2024-10-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0009_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="mini_fb.profile"),
        ),
    ]
